"use strict";var _shortid=_interopRequireDefault(require("shortid"));Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=exports.breakpointsStandard=exports.Mode=void 0;var _mobxReactLite=require("mobx-react-lite"),_utils=require("./utils"),_mobx=require("mobx");require("react-grid-layout/css/styles.css"),require("react-resizable/css/styles.css");function _interopRequireDefault(a){return a&&a.__esModule?a:{default:a}}function _toConsumableArray(a){return _arrayWithoutHoles(a)||_iterableToArray(a)||_nonIterableSpread()}function _nonIterableSpread(){throw new TypeError("Invalid attempt to spread non-iterable instance")}function _iterableToArray(a){if(Symbol.iterator in Object(a)||"[object Arguments]"===Object.prototype.toString.call(a))return Array.from(a)}function _arrayWithoutHoles(a){if(Array.isArray(a)){for(var b=0,c=Array(a.length);b<a.length;b++)c[b]=a[b];return c}}function ownKeys(a,b){var c=Object.keys(a);if(Object.getOwnPropertySymbols){var d=Object.getOwnPropertySymbols(a);b&&(d=d.filter(function(b){return Object.getOwnPropertyDescriptor(a,b).enumerable})),c.push.apply(c,d)}return c}function _objectSpread(a){for(var b,c=1;c<arguments.length;c++)b=null==arguments[c]?{}:arguments[c],c%2?ownKeys(b,!0).forEach(function(c){_defineProperty(a,c,b[c])}):Object.getOwnPropertyDescriptors?Object.defineProperties(a,Object.getOwnPropertyDescriptors(b)):ownKeys(b).forEach(function(c){Object.defineProperty(a,c,Object.getOwnPropertyDescriptor(b,c))});return a}function _defineProperty(a,b,c){return b in a?Object.defineProperty(a,b,{value:c,enumerable:!0,configurable:!0,writable:!0}):a[b]=c,a}function _slicedToArray(a,b){return _arrayWithHoles(a)||_iterableToArrayLimit(a,b)||_nonIterableRest()}function _nonIterableRest(){throw new TypeError("Invalid attempt to destructure non-iterable instance")}function _iterableToArrayLimit(a,b){if(Symbol.iterator in Object(a)||"[object Arguments]"===Object.prototype.toString.call(a)){var c=[],d=!0,e=!1,f=void 0;try{for(var g,h=a[Symbol.iterator]();!(d=(g=h.next()).done)&&(c.push(g.value),!(b&&c.length===b));d=!0);}catch(a){e=!0,f=a}finally{try{d||null==h["return"]||h["return"]()}finally{if(e)throw f}}return c}}function _arrayWithHoles(a){if(Array.isArray(a))return a}var Mode,emptyLayouts={xxl:[],xl:[],lg:[],md:[],sm:[],xs:[]};exports.Mode=Mode,function(a){a.DESIGN="design",a.PRIVIEW="priview"}(Mode||(exports.Mode=Mode={}));// xs	<576px 响应式栅格，可为栅格数或一个包含其他属性的对象	number|object	-
// sm	≥576px 响应式栅格，可为栅格数或一个包含其他属性的对象	number|object	-
// md	≥768px 响应式栅格，可为栅格数或一个包含其他属性的对象	number|object	-
// lg	≥992px 响应式栅格，可为栅格数或一个包含其他属性的对象	number|object	-
// xl	≥1200px 响应式栅格，可为栅格数或一个包含其他属性的对象	number|object	-
// xxl
var breakpointsStandard={xl:1600,lg:1200,md:992,sm:768,xs:576// xs: 0
};exports.breakpointsStandard=breakpointsStandard;var defaultbreakpoints={lg:breakpointsStandard.lg// md: breakpointsStandard.md
},defaultCols={xxl:12,xl:12,lg:8,md:6,sm:4,xs:2},useFPBStore=function(a){var b=(0,_mobxReactLite.useForceUpdate)(),c=(0,_mobxReactLite.useLocalStore)(function(a){return{rowHeight:1,margin:[0,0],layouts:emptyLayouts,breakpoints:defaultbreakpoints,cols:defaultCols,/*********************** */get editingTitle(){return c.editingItem&&c.editingItem.i},get config(){return(0,_mobx.toJS)({datas:c.datas,layouts:c.layouts,cols:c.cols,breakpoints:c.breakpointsArr},{recurseEverything:!0})},mode:Mode.DESIGN,get isPreview(){return c.mode===Mode.PRIVIEW},changeMode:function changeMode(a){c.mode=a.target.value},datas:{},breakpoint:"lg",defaultFormField:!0,get breakpointsConfig(){return{breakpoints:c.breakpointsArr,cols:c.cols}},get breakpointsArr(){return Object.keys(c.breakpoints)},get computedLayout(){return Object.fromEntries(c.breakpointsArr.map(function(a){return[a,c.layouts[a]||[]]}))},hasLayout:function hasLayout(){return 0!==Object.keys(c.datas).length},setDatas:function setDatas(a){var b=Object.fromEntries(Object.entries(a).map(function(a){var b=_slicedToArray(a,2),d=b[0],e=b[1];return[d,_objectSpread({},e,{Component:e.componentId&&c.flatComponents[e.componentId].Component})]}));c.datas=b},setLayouts:function setLayouts(a,b){JSON.stringify(c.layouts)==JSON.stringify(b)||(c.layouts=b)},setBreakpoint:function setBreakpoint(a){c.breakpoint=a},setBreakpointFromEntry:function setBreakpointFromEntry(a){c.breakpoints=Object.fromEntries(a.map(function(a){return[a,breakpointsStandard[a]]}))},setBreakpointConfig:function setBreakpointConfig(a){c.setBreakpointFromEntry(a.breakpoints),c.cols=_objectSpread({},c.cols,{},a.cols),c.setBreakpointSettingVisible(!1)},deleteItem:function deleteItem(a){(0,_mobx.remove)(c.datas,a),b()},get jsConfig(){return(0,_mobx.toJS)({layouts:c.computedLayout,rowHeight:c.rowHeight,margin:c.margin,breakpoints:c.breakpoints,cols:c.cols,onBreakpointChange:c.setBreakpoint,onLayoutChange:c.setLayouts,onResize:c.onResize,onResizeStop:c.onResizeStop,//此处是个问题
isDraggable:null===c.editingItem&&!c.isPreview,isResizable:null===c.editingItem&&!c.isPreview},{recurseEverything:!0})},operatedItem:null,setOperatedItem:function setOperatedItem(a){c.operatedItem=a},onResize:function onResize(a,b,d){c.setOperatedItem(d)},onResizeStop:function onResizeStop(){c.setOperatedItem(null)},findItem:function findItem(a){return c.layouts[c.breakpoint].find(function(c){return c.i===a})},findItemInAllBreakpoints:function findItemInAllBreakpoints(a){return Object.fromEntries(Object.entries(c.layouts).map(function(b){var c=_slicedToArray(b,2),d=c[0],e=c[1];return[d,e.find(function(b){return b.i===a})]}))},getItemHeight:function getItemHeight(a){var b=c.findItem(a);return b&&b.h},caclHeight:function caclHeight(a,b){var d=Math.ceil,e=c.datas[b],f=c.findItem(b),g=c.findItemInAllBreakpoints(b);if(!e.autoHeight)return void Object.values(g).forEach(function(a){a&&(delete a.maxH,delete a.minH)});if(null!==a&&void 0!==a){//store中对应的数据，非布局
var i=d(a/c.rowHeight);f.h=i||30,f.maxH=f.h,f.minH=f.h}},createItem:function createItem(){var a=_shortid.default.generate();// store.layouts[store.breakpoint].push(item);
(0,_mobx.set)(c.datas,a,{i:a,Component:null,autoHeight:!0,componentProps:{},componentId:null,isFormField:null,$id:null}),b(),setTimeout(_utils.doWindowResize,0)},editingItem:null,onItemTypeChange:function onItemTypeChange(a){if(!a)return c.editingItem.Component=null,c.editingItem.componentProps=null,c.editingItem.isFormField=null,void delete c.editingItem.label;var b=c.flatComponents[a];// Object.entries(component.componentProps).
// store.editingItem.componentProps = ;
c.editingItem.Component=b.Component,c.editingItem.componentProps={},b.formField&&(c.editingItem.isFormField=c.defaultFormField,(0,_mobx.set)(c.editingItem,"label","")),c.editingItem.componentId=a},onItemPropsChange:function onItemPropsChange(a,b){c.editingItem[a]=b},get isEditing(){return null!==c.editingItem},setEditingItem:function setEditingItem(a){c.editingItem=a},get flatComponents(){var b={},c=function(){var d=0<arguments.length&&void 0!==arguments[0]?arguments[0]:a.components,e=1<arguments.length?arguments[1]:void 0;d.forEach(function(a){b[a.id]=a,e&&(a.parent=e),a.children&&c(a.children,a)})};return c(),b},get componentGroup(){//有分组组件
var b=a.components.filter(function(a){return a.group}),c=a.components.filter(function(a){return!a.group}),d=_toConsumableArray(new Set(b.map(function(a){return a.group}))),e=[];//无分组组件
return d.forEach(function(a){var c,d=b.filter(function(b){return b.group===a});e.push((c={},_defineProperty(c,a,d),_defineProperty(c,"groupName",a),c))}),c.forEach(function(a){e.push(a)}),e},breakpointSettingVisible:!1,setBreakpointSettingVisible:function setBreakpointSettingVisible(a){c.breakpointSettingVisible=a}}},{components:a.components});return c},_default=useFPBStore;exports.default=_default;
//# sourceMappingURL=useFPBStore.js.map